server:
  port: 8001

#我们可以指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问
spring:
  application:
    name: microservicecloud-dept
eureka:
  client:
    #属性对应服务注册中心的配置内容，指定服务注册中心的位置。
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true     #访问路径可以显示IP地址


info:  #点进去显示的信息
  app.name: microservicecloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$
